#!/usr/bin/env bash
# Tiny colored fetch script
# Requires Typicons Font to display the icons
# elenapan @ github

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

# Items
sep=
s=$d$f0$sep$t

h=
wmname="$(wmctrl -m | awk '$1=="Name:"{print $2;}')"

k=
kernel="$(uname -r | cut -d '-' -f1)"

r=
resolution="$(xrandr | awk -F'[, ]' '$1=="Screen"{print $9" "$10" "$11;}')"

sh=
shell=$(basename $SHELL)

# (\ /)
# ( · ·)
# c(")(")

# (\ /)
# ( . .)
# c(")(")

tput clear
cat << EOF


   (\ /)     $d$f1$h  $t$wmname
   ( $d. .$t)    $f3$k  $t$kernel
   c($f1"$t)($f1"$t)   $f2$sh  $t$shell

EOF

# -- extras
# $f5$r  $t$resolution
