#!/usr/bin/env bash

# setup
STATUS=$(xset -q | grep 'DPMS is' | tail -1 | awk '{print $3;}')

# depends on ~/.Xresources
ON=$( cat ~/.Xresources | grep "*.color14"    | awk '{print $2}')
OFF=$(cat ~/.Xresources | grep "*.foreground" | awk '{print $2}')

case $STATUS in
  'Enabled') # we turn it off if its on
    echo "%{F$OFF}%{F-}" > /tmp/caffeine
    xset s off
    xset -dpms
   ;;
  'Disabled')
    echo "%{F$ON}%{F-}" > /tmp/caffeine
    xset s on
    xset +dpms
    ;;
esac
