#! /usr/bin/env zsh

set -e

#   settings
COLOUR_OFF="%{F#232530}"
COLOUR_ON="%{F#B877DB}"

FOCUS="%{A1::}"

FOCUS="${FOCUS}${COLOUR_OFF}%{F-}%{A}"

TRAY="${GENERAL}"
echo "${TRAY}" > /tmp/xmonad-states

# keep track of the number of notifications
NUMNOT=0

#  action stations
dbus-monitor --session --profile "interface='org.freedesktop.Notifications'" |
  while read line; do
    SENDER=$(echo "${line}" | grep -Ev '#|NameAcquired|NameLost' | awk '{print $4;}')
    [[ $SENDER ]] &&
      SAPP=$(gdbus call \
           --session \
           --dest org.freedesktop.DBus \
           --object-path /\
           --method org.freedesktop.DBus.GetConnectionUnixProcessID\
           $SENDER |\
           awk '{ gsub(",)", "", $2); print $2};' |\
           xargs -I '{}' ps -p '{}' -o comm= ) ||
      SAPP=
    TYPE=$(echo "${line}" | grep -Ev '#|NameAcquired|NameLost' | awk '{print $NF;}')
    [[ $TYPE == 'Notify' ]] && NUMNOT=$(($NUMNOT+1))
    [[ $TYPE == 'NotificationClosed' ]] && NUMNOT=$(($NUMNOT-1))

    case $NUMNOT in
      0) FOCUS="${FOCUS}${COLOUR_OFF}%{F-}%{A}";;
      *) FOCUS="${FOCUS}${COLOUR_ON}%{F-}%{A}";;
    esac
        
    # [[ $SAPP ]] && case $SAPP in
    #   '.geary-wrapped')
    #     [[ $TYPE == 'Notify' ]] && GEARY="${FOCUS_GEARY}${COLOUR_ON}%{F-}%{A}"
    #     [[ $TYPE == 'CloseNotification' ]] && GEARY="${FOCUS_GEARY}${COLOUR_OFF}%{F-}%{A}"
    #     ;;
    #   '.discord')
    #     [[ $TYPE == 'Notify' ]] && DISCORD="${COLOUR_ON}%{F-}%{A}"
    #     [[ $TYPE == 'CloseNotification' ]] && DISCORD="${COLOUR_OFF}%{F-}%{A}"
    #     ;;
    # esac


    [[ $SENDER ]] &&
      TRAY="${FOCUS}" &&
      echo "${TRAY}" > /tmp/xmonad-states
  done
