#! /usr/bin/env zsh

set -e

#   settings
COLOUR_OFF="%{F#232530}"
COLOUR_ON="%{F#B877DB}"

FOCUS_GEARY="%{A1:wmctrl -a geary:}"
FOCUS_DCORD="%{A1:wmctrl -a Discord:}"

GEARY="${FOCUS_GEARY}${COLOUR_OFF}%{F-}%{A}"
DISCORD="${FOCUS_DCORD}${COLOUR_OFF}%{F-}%{A}"

TRAY="${GEARY} ${DISCORD}"
echo "${TRAY}" > /tmp/xmonad-states


#  action stations
dbus-monitor --session --profile "interface='org.freedesktop.Notifications'" |
  while read line; do
    SENDER=$(echo "${line}" | grep -Ev '#|NameAcquired|NameLost' | awk '{print $4;}')
    [[ $SENDER ]] &&
      SAPP=$(gdbus call \
           --session \
           --dest org.freedesktop.DBus \
           --object-path /\
           --method org.freedesktop.DBus.GetConnectionUnixProcessID\
           $SENDER |\
           awk '{ gsub(",)", "", $2); print $2};' |\
           xargs -I '{}' ps -p '{}' -o comm= ) ||
      SAPP=
    TYPE=$(echo "${line}" | grep -Ev '#|NameAcquired|NameLost' | awk '{print $NF;}')
    [[ $SAPP ]] && case $SAPP in
      '.geary-wrapped')
        [[ $TYPE == 'Notify' ]] && GEARY="${FOCUS_GEARY}${COLOUR_ON}%{F-}%{A}"
        [[ $TYPE == 'CloseNotification' ]] && GEARY="${FOCUS_GEARY}${COLOUR_OFF}%{F-}%{A}"
        ;;
      '.discord')
        [[ $TYPE == 'Notify' ]] && DISCORD="${COLOUR_ON}%{F-}%{A}"
        [[ $TYPE == 'CloseNotification' ]] && DISCORD="${COLOUR_OFF}%{F-}%{A}"
        ;;
    esac


    [[ $SENDER ]] &&
      TRAY="${GEARY} ${DISCORD}" &&
      echo "${TRAY}" > /tmp/xmonad-states
  done

# dbus-monitor "${WATCH1}" "${WATCH2}" "${WATCH3}" | \
# awk '
# /member=NoteAdded/ { getline; print "Created note " substr($2,7) }
# /member=NoteSaved/ { getline; print "Added note " substr($2,7) }
# /member=NoteDeleted/ { getline; print "Deleted note " substr($2,7) }
