#!/usr/bin/env sh


AVAILABLE=$(wmctrl -l |\
  cut -d' ' -f1 |\
  xargs -I@ xprop -id @ |\
  grep 'WM_CLASS(STRING)' |\
  awk '{print tolower($NF);}' |\
  xargs -I@ echo "^ca(1, wmctrl -x -a @)@^ca()"
)

LINES=$(echo "$AVAILABLE" | wc -l)

{ echo "^fn(Fira Sans:style=Bold:size=12)Available windows^fn()";
  echo "$AVAILABLE";
} | dzen2 \
          -fn 'Fira Sans:size=10' \
          -l $LINES \
          -e 'onstart=uncollapse;\
              button1=exit;\
              button4=scrollup;\
              button5=scrolldown;' \
          -ta c -sa c\
          -tw 371 -w 371 \
          -h 45 \
          -x 0 \
          -y 40 \
          -m \
          -p 1 # cba figuring out the on mouse exit close part yet
