#!/usr/bin/env bash

pkill polybar

desktop=$(echo $DESKTOP_SESSION)

case $desktop in
  none+i3)
    if ! pgrep -x polybar; then
      polybar i3 &
      ln -s /tmp/polybar_mqueue.$! /tmp/i3-mode
    else
      pkill -USR1 polybar
    fi
    ;;
  none+xmonad)
    if ! pgrep -x polybar; then
      polybar xmonad &
      ln -s /tmp/polybar_mqueue.$! /tmp/xmonad-mode
    else
      pkill -USR1 polybar
    fi
    ;;
esac
